spring:
  datasource:
    url: jdbc:mysql://localhost:3009/wanted
    username: wanted
    password: wanted12!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
